site_name: monoheart电波站
theme:
  favicon: img/favicon.png
  name: 'material'
  logo: img/favicon.png
  palette:
    primary: teal
    accent: teal
nav:
  - 首页: index.md
  - 书: media/books.md
  - 影: media/movies.md
  - 剧: media/tv.md
  - 游戏: media/games.md
  - 文章: posts/index.md
extra_css:
  - stylesheets/extra.css